config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :services

  resources :bookings, only: [:index, :new, :create, :destroy, :edit, :update]
  get '/dashboard', to: 'bookings#dashboard'
  get '/users', to: 'pages#user_index'
  get '/user/:id', to: 'pages#user_show', as: :user
  get '/user/:id/edit', to: 'pages#user_edit', as: :edit_user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  #skip_before_action :authenticate_user!, only: :home

  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  def index
    @bookings = Booking.all
  end

  def show
  end

  def new

  @booking = Booking.new



  end

  def edit
    @booking = Booking.find(params[:id])
    @user = current_user
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dashboard_path(current_user)
  end

  def create
    @service = Service.find(params[:booking][:service_id].to_i)
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.service = @service
    @booking.user = @user
    if @booking.save
      redirect_to dashboard_path(current_user)
    else
      render :new
    end
  end

  # def update
  #   respond_to do |format|
  #     if @booking.update(booking_params)
  #       redirect_to booking_path(@booking)
  #     else
  #       render :edit
  #     end
  #   end
  # end

  def destroy
    @booking.destroy
    redirect_to dashboard_path
  end

  def dashboard
    @bookings = Booking.where(user: current_user)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date, :service_id, :user_id)
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


  <div class="form-inputs">
    <%= f.association :service, collection: Service.all %>
    <%= f.input :date %>
  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>



<!-- simple_form_for @user do |f|
  f.association :company          # Company.all
end
 -->

app/views/bookings/dashboard.html.erb
<div class="container">
<%= link_to "See my profile", user_path(current_user), class: "btn btn-suc" %>
  <div class="row">
    <div class="dashboard-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url(<%= image_path 'dashboard_background.jpg' %>);">
      <h1>My Dashboard</h1>
      <div class="profile-image">
        <% if user_signed_in? %>
          <%= cl_image_tag current_user.photo, class: "coach-card-avatar", width: 180, height: 180, crop: :thumb, gravity: :face %>
        <% end %>
      </div>
    </div>
    <div class="welcome">
      <h2>
        <% if user_signed_in? %>
          Hello <%= current_user.name%> !
        <% end %>
      </h2>
    </div>
  </div>
  <div class="dashboard">
    <div class="calendar">
      <h3>Calendar</h3>
      <div class="date-calendar">
        <% if @bookings.empty? %>
          <h3>No bookings yet</h3>
        <% else %>
          <h3><%= Date.today %></h3>
          <% @bookings.where("date BETWEEN ? AND ?", DateTime.now, DateTime.tomorrow).each do |booking| %>
            <div class="card-product">
              <%= cl_image_tag booking.service.user.photo, class: "coach-card-avatar", width: 150, height: 150, crop: :thumb, gravity: :face %>
              <div class="card-product-infos">
                <h2><%= booking.service.name%></h2>
                <p><%=booking.date.strftime("%d %B %Y")%>
                at <%=booking.date.strftime("%H:%M")%> h
                  with <%= booking.service.user.name  %></p>
                  <div class="button-link">
                    <%= link_to "Delete", booking_path(booking), class: "btn btn-book", method: :delete, data: { confirm: 'Are you sure you want to cancel this meeting?' } %>
                  </div>
              </div>
            </div>
          <% end %>
        <% end %>
<!--         </div> -->
      </div>
    </div>
    <div class="booking">
      <h3>My Bookings</h3>
      <div class="details_booking">
        <% @bookings.order(date: :desc).each do |booking| %>
          <div class="card-product">
            <%= cl_image_tag booking.service.user.photo, class: "coach-card-avatar", width: 150, height: 150, crop: :thumb, gravity: :face %>
            <div class="card-product-infos">
              <h2><%= booking.service.name%></h2>
              <p><%=booking.date.strftime("%d %B %Y")%>
              at <%=booking.date.strftime("%H:%M")%> h
                with <%= booking.service.user.name  %></p>
                <div class="button-link">
                <%= link_to "Delete", booking_path(booking), class: "btn btn-book",method: :delete, data: { confirm: 'Are you sure you want to cancel this meeting?' } %>
                <%= link_to "Change", edit_booking_path(booking), class: "btn btn-book" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row button">
    <%= link_to "Go to Homepage", root_path, class: "btn-suc text-center" %>
  </div>
</div>

<!-- <div class="flex-container">
  <p>just a try</p>



  <div class="flex-item">
     <p>just a try</p>


  </div>
  <div class="flex-item">...</div>
  <div class="flex-item">...</div>
</div> -->

app/views/bookings/edit.html.erb
<div class="wrapper">
  <div class="container" >
    <div class="nice-form" style="background-image: url(<%= image_path 'coach.jpg' %>);">
      <div class="form-only">
      <h1>Book a Coach</h1>
        <%= simple_form_for ([@service, @booking]) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.association :service, collection: Service.all, value_method: :id, label_method: :name%>
        <%= f.input :date, class: "transperent" %>
        <div class="form-actions">
        <%= f.button :submit, class: "btn-suc", value: "Change !"%>
        </div>
        <br>
        <div class="form-actions">
          <%= link_to "Cancel", dashboard_path, class: "btn btn-suc" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
        <td><%= booking.date %></td>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<div class="wrapper">
  <div class="container" >
    <div class="nice-form" style="background-image: url(<%= image_path 'coach.jpg' %>);">
      <div class="form-only">
      <h1>Book a Coach</h1>
        <%= simple_form_for ([@service, @booking]) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.association :service, collection: Service.all, value_method: :id, label_method: :name%>
        <%= f.input :date, class: "transparent" %>
        <div class="form-actions">
        <%= f.button :submit, class: "btn-suc", value: "Get fit !"%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row text-center">
  <%= link_to "Back to Homepage", root_path, class: "btn btn-suc text-center" %>
      <%= link_to 'Back to my Dashboard', dashboard_path, class: "btn-suc text-center" %>
</div>