config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :services

  resources :bookings, only: [:index, :new, :create, :destroy, :edit, :update]
  get '/dashboard', to: 'bookings#dashboard'
  get '/users', to: 'pages#user_index'
  get '/user/:id', to: 'pages#user_show', as: :user
  get '/user/:id/edit', to: 'pages#user_edit', as: :edit_user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by GetACoach
  </div>
</div>

app/views/pages/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Dashboard", "/dashboard", class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "My Bookings", "/bookings", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'background.jpg' %>);">
  <div class="banner-content">
    <h1>Find your coach</h1>
    <%= form_tag services_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Let's get fit in ..."
      %>
    <% end %>
    <div class="text-search">
      search by discipline or by city
    </div>
    <%#= link_to "Search", services_path, class: "btn-coaches text-center" %>
  </div>
</div>


<div class="container">
  <div class="row home-description">
    <h2>How It Works</h2>
    <p>Get A Coach is the most convenient place for you to connect with a personal coach - wherever you are! Are you looking for a coach to push you to run your fastest 10k? Or have you always wanted to learn some fiery Zumba moves? Whatever your goals and interests are, we have the right coach for you!</p>
    <div class="flex-container">
      <div class="flex-item">
        <%= link_to "<i class='fas fa-search'></i>
          <br class='montserrat'>See all Coaches"
      .html_safe, users_path, class: "montserrat" %>
      </div>
      <div class="flex-item">
        <a href="#" ><i class="fas fa-user-plus"></i>
          <br class="montserrat">Sign Up</a>
      </div>
      <div class="flex-item">
        <%= link_to "<i class='fas fa-calendar-check'></i>
          <br class='montserrat'>Book a Session"
      .html_safe, services_path, class: "montserrat" %>
      </div>
<!--       <div class="flex-item">
        <a href="#" ><i class="fas fa-dumbbell"></i>
          <br class="montserrat">Get Fit!</a>
      </div> -->
    </div>
  </div>
  <h2 class="text-center">Our Coaches</h2>
      <% @users.each do |user|%>
        <div class="col-xs-12 col-lg-4 coach-card">
            <%= cl_image_tag user.photo, class: "coach-card-avatar", width: 150, height: 150, crop: :thumb, gravity: :face %>
            <h4><%=link_to user.name, user_path(user) %></h4>
            <p><%= user.category %></p>
        </div>
        <% end %>
    </div>
<!--     <div class="row button">
      <%= link_to "See all Coaches", users_path, class: "btn-coaches text-center" %>
    </div> -->
</div>

<div class="container">
    <div class="row table">
      <h2 class="text-center">Our Disciplines</h2>
        <table style="width:100%">
          <tr>
            <td><a href="#">Basketball</a></td>
            <td><a href="#">Running</a></td>
            <td><a href="#">Tennis</a></td>
            <td><a href="#">Zumba</a></td>
            <td><a href="#">Kickboxing</a></td>
          </tr>
          <tr>
            <td><a href="#">Frisbee</a></td>
            <td><a href="#">Swimming</a></td>
            <td><a href="#">Football</a></td>
            <td><a href="#">Karate</a></td>
            <td><a href="#">Oriental Dance</a></td>
          </tr>
          <tr>
            <td><a href="#">Bodybuilding</a></td>
            <td><a href="#">Yoga</a></td>
            <td><a href="#">Boxing</a></td>
            <td><a href="#">Inline Skating</a></td>
            <td><a href="#">Ballet</a></td>
          </tr>
          <tr>
            <td><a href="#">Pilates</a></td>
            <td><a href="#">Strength Training</a></td>
            <td><a href="#">Crossfit</a></td>
            <td><a href="#">Nordic Walking</a></td>
            <td><a href="#">Calisthenics</a></td>
          </tr>
          <tr>
            <td><a href="#">Roller Skating</a></td>
            <td><a href="#">Salsa</a></td>
            <td><a href="#">Jiu Jitsu</a></td>
            <td><a href="#">Baseball</a></td>
            <td><a href="#">Hip Hop</a></td>
          </tr>
        </table>
        <div class="row button">
          <%= link_to "See all Services", services_path, class: "btn-coaches text-center" %>
        </div>
    </div>
</div>

app/views/pages/user_index.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">Find Your Future Coach</h2>
      <% @users.each do |user|%>
        <div class="col-xs-12 col-lg-4 coach-card">
             <%= cl_image_tag user.photo, class: "coach-card-avatar", width: 150, height: 150, crop: :thumb, gravity: :face %>
            <h4><%=link_to user.name, user_path(user) %></h4>
            <p><%= user.category %></p>
        </div>
      <% end %>
  </div>
  <div class="row button">
    <%= link_to "Go back", root_path, class: "btn-coaches text-center" %>
  </div>
</div>

app/views/pages/user_show.html.erb
<div class="row editing text-center">
  <%= link_to "Add a new service", new_service_path, class: "btn btn-coaches" %>
  <%= link_to "Edit my Profile", edit_user_registration_path, class: "btn-coaches" %>
</div>

<div class="container">
  <div class="row">
    <div class="profile-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url(<%= image_path 'profile_background.jpg' %>);">
      <div class="profile-card-description">
       <h2><%= @user.name %></h2>
       <p>Age: <%= @user.age %></p>
       <p>City: <%= @user.city %></p>
       <p>Specialty: <%= @user.category %></p>
      </div>
      <div class="profile-image">
        <%= cl_image_tag @user.photo, class: "coach-card-avatar", width: 180, height: 180, crop: :thumb, gravity: :face %>
      </div>
    </div>
  </div>
  <div class="profile-background">
    <h3>My Background</h3>
    <p><%= @user.background %></p>
  </div>
  <div class="row service-description">
    <h2 text-center> My Services</h2>
    <div class="profile-service">
      <% @services.each do |service| %>
       <div class=profile-service-title>
        <%= service.name %>
       </div>
       <div class="profile-service-info">
        <p><%= service.description %></p>
        <p>Where: <%= service.address %></p>
        <p>Price: <%= service.price %>€ / hour</p>
       </div>
      <% end %>
      <% if current_user.id = @user.id %>
        <%= link_to "Update my service", edit_service_path(@user.services.first), class: "btn-coaches" %>
        <%= link_to "Delete this service", service_path(@user.services.last), class: "btn-coaches",  method: :delete,
          data: { confirm: "Are you sure?" } %>
      <% else %>
        <%= link_to "Book now", new_booking_path, class: "btn-coaches" %>
      <% end %>
    </div>
  </div>
  <div class="row-link text-center">
    <%= link_to "Return to homepage", root_path, class: "btn-coaches" %>
  </div>
</div>